### ISSUE TITLE
system tests: LOCAL_IP_ENV setting ignored/broken in some cases

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#1185]
`Building.md` mentions a `LOCAL_IP_ENV` environment variable, which it says controls what local IP etcd will bind to but it doesn't seem to be honoured by all of the test code:

I ran `sudo LOCAL_IP_ENV=172.17.0.1 make st` and it looked like it started etcd correctly:

```
docker run --detach \
--net=host \
--name calico-etcd quay.io/coreos/etcd:v2.0.11 \
--advertise-client-urls "http://172.17.0.1:2379" \
--listen-client-urls "http://172.17.0.1:2379,http://127.0.0.1:2379"
```

But the tests then fail at this stage, using the wrong IP (`192.168.171.128`):

```
======================================================================
ERROR: Test using different AS number for the node-to-node mesh.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests/st/test_base.py", line 45, in setUp
    self.curl_etcd("calico", options=["-XDELETE"])
  File "/tests/st/test_base.py", line 118, in curl_etcd
    shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'curl -sL http://192.168.171.128:2379/v2/keys/calico?recursive=true -XDELETE' returned non-zero exit status 7
```

**Comment by tomdee** [comment]
@lwr20 You might be better placed to resolve this than me?

**Comment by lwr20** [comment]
Yep - I'll take a look today
