### ISSUE TITLE
make st relies on specific iptables configuration

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#1186]
I'm trying to test golang felix with the calico-containers STs but I'm having trouble getting them to run.  They seem to hang at this stage:

```docker exec -it host1 sh -c 'export ETCD_AUTHORITY=192.168.171.128:2379; export ETCD_SCHEME=http; export ETCD_CA_CERT_FILE=; export ETCD_CERT_FILE=; export ETCD_KEY_FILE=; /code/dist/calicoctl bgp default-node-as 4294.566'```

Eventually timing out with a failure to reach etcd.  I don't think the go code has been reached yet.

```
======================================================================
ERROR: Test using different AS number for the node-to-node mesh.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests/st/bgp/test_bgp_config.py", line 75, in test_as_num
    host1.calicoctl("bgp default-node-as %s" % LARGE_AS_NUM)
  File "/tests/st/utils/docker_host.py", line 158, in calicoctl
    return self.execute(calicoctl + " " + command)
  File "/tests/st/utils/docker_host.py", line 122, in execute
    return log_and_run(command)
  File "/tests/st/utils/utils.py", line 76, in log_and_run
    raise CommandExecError(e)
CommandExecError: Command docker exec -it host1 sh -c 'export ETCD_AUTHORITY=192.168.171.128:2379; export ETCD_SCHEME=http; export ETCD_CA_CERT_FILE=; export ETCD_CERT_FILE=; export ETCD_KEY_FILE=; /code/dist/calicoctl bgp default-node-as 4294.566' failed with RC 1 and output:
set_default_node_as: Error accessing etcd (Connection to etcd failed due to
MaxRetryError("HTTPConnectionPool(host='192.168.171.128', port=2379): Max
retries exceeded with url: /v2/keys/calico/bgp/v1/global/as_num (Caused by
ConnectTimeoutError(<urllib3.connection.HTTPConnection object at
0x7fa4968f1790>, 'Connection to 192.168.171.128 timed out. (connect
timeout=60)'))",)).  Is etcd running?

```

Trying to reach etcd from one of the host containers fails if I try it manually:

```
docker exec -ti host1 curl http://192.168.171.128:2379/v2/keys
```

I see one-way traffic in tcpdump:

```
11:32:40.611933 02:42:ac:11:00:02 > 02:42:12:21:81:d2, ethertype IPv4 (0x0800), length 74: 172.17.0.2.36876 > 192.168.171.128.2379: Flags [S], seq 3314834407, win 29200, options [mss 1460,sackOK,TS val 213840 ecr 0,nop,wscale 7], length 0
11:32:40.939402 02:42:ac:11:00:02 > 02:42:12:21:81:d2, ethertype IPv4 (0x0800), length 74: 172.17.0.2.36878 > 192.168.171.128.2379: Flags [S], seq 3610087760, win 29200, options [mss 1460,sackOK,TS val 213922 ecr 0,nop,wscale 7], length 0
```

Lance doesn't see the same issue.  Reboot didn't solve it.

**Comment by fasaxc** [comment]
OK, this turned out to be a misconfigured iptables INPUT chain policy.  For some reason my INPUT chain had policy DROP, which was dropping the etcd traffic.  Lance's machines had policy ACCEPT.
```
sudo iptables-save -t filter | grep ':INPUT'
```
is one way to find out the policy
```
sudo iptables -P INPUT ACCEPT
```
to change.

**Comment by fasaxc** [comment]
Could/should we make the STs more robust to this sort of config change?  If we ran etcd in a container with its own IP (rather than host networking), wouldn't that do the trick?
