### ISSUE TITLE
calicoctl starts node even without etcd connection

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-containers#1294]
Seems `calicoctl` no longer fails to start node if it can't connect to etcd. When launched, we're left with a immediately dead container, and a return code of `0`.

```
turk:calico/ (master✗) $ sudo calicoctl node run                                              [10:17:52]
Running command to load modules: modprobe -a xt_set ip6_tables
Enabling IPv4 forwarding
Enabling IPv6 forwarding
Increasing contrack limit
Running the following command:

docker run -d --net=host --privileged --name=calico-node -e HOSTNAME=durk -e IP6= -e CALICO_NETWORKING_BACKEND=bird -e ETCD_SCHEME=http -e CALICO_LIBNETWORK_ENABLED=true -e IP= -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_ENDPOINTS= -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules calico/node:v1.0.0-beta

turk:calico/ (master✗) $ echo $?                                                              [10:17:54]
0
turk:calico/ (master✗) $ docker ps -a                                                         [10:17:56]
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                     PORTS               NAMES
630d945c26cf        calico/node:v1.0.0-beta   "start_runit"       5 seconds ago       Exited (1) 4 seconds ago                       calico-node
turk:calico/ (master✗) $ docker logs calico-node                                              [10:17:59]
Traceback (most recent call last):
  File "<string>", line 346, in <module>
  File "<string>", line 297, in main
Waiting for etcd connection...
No IP provided. Using detected IP: 172.18.0.1
  File "<string>", line 210, in warn_if_hostname_conflict
  File "site-packages/pycalico/datastore.py", line 137, in wrapped
pycalico.datastore_errors.DataStoreError: get_host_bgp_ips: Error accessing etcd (Connection to etcd failed due to MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=2379): Max retries exceeded with url: /v2/keys/calico/bgp/v1/host/durk/ip_addr_v4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd67685110>: Failed to establish a new connection: [Errno 111] Connection refused',))",)).  Is etcd running?
startup returned -1
Calico node failed to start
```

**Comment by caseydavenport** [comment]
@djosborne Thoughts on a proposed fix?

Not sure what the priority of this is.  The `calico/node` container also has an option to wait for an etcd connection, which we should expose through calicoctl if it isn't already.  See `WAIT_FOR_DATASTORE=true`

**Comment by djosborne** [comment]
I thought we used to attach to `startup.py` and return its error code since it makes use of the etcd connection
