### ISSUE TITLE
Certificate Authority is required and must be readable

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#1307]
Originally raised by @spuranam

@caseydavenport i am running into issues even after upgrading to 1.6.

OS: CoreOS v1192.2.0
Calico Images used:
quay.io/calico/node:v0.23.0
calico/kube-policy-controller:v0.4.0
quay.io/calico/leader-elector:v0.1.0

I have verified the certs are present in the filesystem and are readable.

## calico node.service
```bash
[Unit]
Description=Calico per-host agent
Requires=network-online.target
After=network-online.target

[Service]
Slice=machine.slice
PermissionsStartOnly=true
Environment=ETCD_CA_CERT_FILE=/etc/ssl/etcd/ca.pem
Environment=ETCD_CERT_FILE=/etc/ssl/etcd/etcd-client.pem
Environment=ETCD_KEY_FILE=/etc/ssl/etcd/etcd-client-key.pem
Environment=CALICO_DISABLE_FILE_LOGGING=true
Environment=HOSTNAME=${ADVERTISE_IP}
Environment=IP=${ADVERTISE_IP}
Environment=FELIX_FELIXHOSTNAME=${ADVERTISE_IP}
Environment=CALICO_NETWORKING=true
Environment=NO_DEFAULT_POOLS=true
Environment=ETCD_ENDPOINTS=${ETCD_ENDPOINTS}

ExecStartPre=/bin/mkdir /var/run/calico
ExecStart=/usr/bin/rkt run --inherit-env --stage1-from-dir=stage1-fly.aci \
--volume=var-run-calico,kind=host,source=/var/run/calico \
--volume=modules,kind=host,source=/lib/modules,readOnly=false \
--mount=volume=modules,target=/lib/modules \
--volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true \
--mount=volume=dns,target=/etc/resolv.conf \
--volume=etcd-tls-certs,kind=host,source=/etc/ssl/etcd,readOnly=true \
--mount=volume=dns,target=/etc/resolv.conf \
--mount=volume=etcd-tls-certs,target=/etc/ssl/etcd \
--mount=volume=var-run-calico,target=/var/run/calico \
--trust-keys-from-https quay.io/calico/node:v0.23.0
KillMode=mixed
Restart=always
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

## /etc/kubernetes/cni/net.d/10-calico.conf on master
```json
{
    "name": "calico",
    "type": "flannel",
    "delegate": {
        "type": "calico",
        "etcd_endpoints": "https://10.50.65.20:2379,https://10.50.65.21:2379,https://10.50.65.22:2379",
"etcd_key_file": "/etc/ssl/etcd/etcd-client-key.pem",
"etcd_cert_file": "/etc/ssl/etcd/etcd-client.pem",
"etcd_ca_cert_file": "/etc/ssl/etcd/ca.pem",
        "log_level": "none",
        "log_level_stderr": "info",
        "hostname": "10.50.65.20",
        "policy": {
            "type": "k8s",
            "k8s_api_root": "http://127.0.0.1:8080/api/v1/"
        }
    }
}
```

## /etc/kubernetes/cni/net.d/10-calico.conf on worker
```json
{
    "name": "calico",
    "type": "flannel",
    "delegate": {
        "type": "calico",
        "etcd_endpoints": "https://10.50.65.20:2379,https://10.50.65.21:2379,https://10.50.65.22:2379",
"etcd_key_file": "/etc/ssl/etcd/etcd-client-key.pem",
"etcd_cert_file": "/etc/ssl/etcd/etcd-client.pem",
"etcd_ca_cert_file": "/etc/ssl/etcd/ca.pem",
        "log_level": "debug",
        "log_level_stderr": "info",
        "hostname": "10.50.65.40",
        "policy": {
            "type": "k8s",
            "k8s_api_root": "https://10.59.65.40:443/api/v1/",
            "k8s_client_key": "/etc/kubernetes/ssl/worker-key.pem",
            "k8s_client_certificate": "/etc/kubernetes/ssl/worker.pem"
        }
    }
}
```

## Log entries from /var/log/calico/cni/cni.log
```
[kube-system/heapster-v1.2.0-3646253287-iteb7] INFO Starting Calico CNI plugin execution
[kube-system/heapster-v1.2.0-3646253287-iteb7] ERROR Unhandled Exception killed plugin
Traceback (most recent call last):
  File "<string>", line 773, in main
  File "<string>", line 64, in __init__
  File "site-packages/pycalico/datastore.py", line 229, in __init__
DataStoreError: Invalid ETCD_CA_CERT_FILE. Certificate Authority cert is required and must be a readable file path. Value provided:
```

## log entries from journalctl -u kubelet.service -f
```
ERROR CNI Error:
{
  "msg": "Unhandled Exception killed plugin",
  "cniVersion": "0.1.0",
  "code": 100,
  "details": null
}
Traceback (most recent call last):
  File "<string>", line 773, in main
  File "<string>", line 64, in __init__
  File "site-packages/pycalico/datastore.py", line 229, in __init__
DataStoreError: Invalid ETCD_CA_CERT_FILE. Certificate Authority cert is required and must be a readable file path. Value provided:
```

**Comment by caseydavenport** [comment]
@spuranam Looks like the CNI plugin is having trouble finding the CA cert.

Could you ensure that this file exists within the kubelet container? `/etc/ssl/etcd/ca.pem`

It looks like you've mounted the directory properly, but best to double check.

**Comment by caseydavenport** [comment]
Could you make sure that you've mounted `/etc/cni/net.d` and `/etc/ssl/etcd` into the kubelet container (if you're running it as a container).

Looks like the CNI plugin isn't getting the right CNI network config passed to it.

**Comment by spuranam** [comment]
@caseydavenport i finally got calico network policies to work with TLS enabled etcd, using both systemd managed instance and hosted calico. I posted my configuration for anyone else who might be running into same issues https://gist.github.com/spuranam/e8584e6cac75663814c90ba7b58cba06

**Comment by caseydavenport** [comment]
Awesome, thanks for checking back in and providing that config :)
