### ISSUE TITLE
Calicoctl node prints exception when Docker is not ready for requests

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-containers#592]
I hit this issue when running on AWS with CoreOS using cloud-config.

I believe what happened is that I ran the instance creation scriptsl and was able to SSH into the machines before the cloud-config had finished executing its install scripts.  I don't think Docker was completely installed when I ran `calicoctl node`.

We should quit, saying that Docker is not installed correctly, when we hit an issue like this.

```
core@ip-172-35-0-131 ~ $ sudo calicoctl node --libnetwork
ERROR: Docker server must support Docker Remote API v1.21 or greater.
No IP provided. Using detected IP: 172.35.0.131
APIError: 404 Client Error: Not Found ("404 page not found")

Traceback (most recent call last):
  File "<string>", line 104, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 199, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 258, in node_start
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 539, in warn_if_hostname_conflict
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 440, in containers
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 126, in _result
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 122, in _raise_for_status
APIError: 404 Client Error: Not Found ("404 page not found")
```

**Comment by tomdee** [comment]
Fixed by #862
