### ISSUE TITLE
User can't choose to talk to insecure registry

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-containers#728]
```
sudo /opt/bin/calicoctl node --node-image=kube-scale-master:5000/calico-node
No IP provided. Using detected IP: 10.240.0.25
Pulling Docker image kube-scale-master:5000/calico-node

DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.

Traceback (most recent call last):
  File "<string>", line 118, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 225, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 367, in node_start
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 397, in _start_node_container
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 725, in _find_or_pull_node_image
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 879, in pull
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.auth.auth", line 59, in resolve_repository_name
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.auth.auth", line 38, in expand_registry_url
DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```

A workaround would be to use docker to pull the image e.g. `docker pull kube-scale-master:5000/calico-node` does work.

**Comment by tomdee** [comment]
Docker pull has a load of options
```
Params:

repository (str): The repository to pull
tag (str): The tag to pull
stream (bool): Stream the output as a generator
insecure_registry (bool): Use an insecure registry
auth_config (dict): Override the credentials that Client.login has set for this request  auth_config should contain the username and password keys to be valid.
```

We shouldn't try to duplicate them - instead we should just provide a --no-pull option.

**Comment by tomdee** [comment]
Discussed with @caseydavenport and agreed on the --no-pull type option
