### ISSUE TITLE
CNI plugin timing out in k8s coreos-vagrant demo

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#883]
Seems like ~ 1 in 5 times I run the demo I get this error in my CNI log, preventing containers from starting:

```
2016-03-23 00:59:47,280 2190 [calico-system/calico-policy-agent-7azmj] ERROR Unhandled Exception killed plugin
Traceback (most recent call last):
  File "<string>", line 683, in main
  File "<string>", line 163, in execute
  File "<string>", line 222, in add
  File "<string>", line 246, in _add_new_endpoint
  File "<string>", line 554, in _provision_veth
  File "pycalico/datastore_datatypes.py", line 325, in provision_veth
  File "pycalico/netns.py", line 167, in move_veth_into_ns
  File "pycalico/netns.py", line 320, in check_output
  File "subprocess32.py", line 635, in check_output
TimeoutExpired: Command '['ip', 'netns', 'exec', '60243770f09211e5a9230800274b98c8', 'ip', 'link', 'set', 'dev', 'tmp60215b7cf09', 'name', 'eth0']' timed out after 5 seconds
```

**Comment by caseydavenport** [comment]
I think this is a duplicate of https://github.com/projectcalico/calico-cni/issues/135
