### ISSUE TITLE
Calicoctl doesn't work with non default Docker configuration

### ISSUE THREAD

**Issue by MatMeredith** [projectcalico/calico-containers#884]
I added an entry to docker.cfg to change the default output of "docker ps"

"psFormat":"table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.RunningFor}}"

Calicoctl now fails.

 calicoctl
Traceback (most recent call last):
  File "<string>", line 64, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/bgp.py", line 38, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/connectors.py", line 44, in <module>
  File "site-packages/docker/client.py", line 56, in __init__
  File "site-packages/docker/auth/auth.py", line 182, in load_config
  File "site-packages/docker/auth/auth.py", line 118, in parse_auth
TypeError: string indices must be integers
calicoctl returned -1

**Comment by TrimBiggs** [comment]
Hi @MatMeredith,

I've created a config file at `~/.docker/config.json` with the contents:
```
{
"psFormat":"table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.RunningFor}}"
}
```

And ran `calicoctl` without issues.

What version of Docker/Claicoctl were you using? What else does your config file have?

**Comment by MatMeredith** [comment]
In answer to your questions…

-          Docker version 1.9.0, build 76d6bc9

-          Calicoctl 0.17.0-dev

Box is installed using a modified version of the Vagrantfile from the “Vagrant install with Ubuntu” option here: https://github.com/projectcalico/calico-containers/tree/master/docs/calico-with-docker/docker-network-plugin (albeit not quite the latest version).   Changes are just to add additional packages – I think all of the Calico / Docker setup is unchanged from the original.

Sample output from calicoctl with and without config.json below.   Also contents of config.json.

Mat

----------

vagrant@tiger-01:~$ calicoctl
Override the host:port of the ETCD server by setting the environment variable
ETCD_AUTHORITY [default: 127.0.0.1:2379]

Usage: calicoctl <command> [<args>...]

    status            Print current status information
    node              Configure the main calico/node container and establish Calico networking
    container         Configure containers and their addresses
    profile           Configure endpoint profiles
    endpoint          Configure the endpoints assigned to existing containers
    pool              Configure ip-pools
    bgp               Configure global bgp
    ipam              Configure IP address management
    checksystem       Check for incompatibilities on the host system
    diags             Save diagnostic information
    version           Display the version of calicoctl
    config            Configure low-level component configuration

See 'calicoctl <command> --help' to read about a specific subcommand.

vagrant@tiger-01:~$ mv ~/.docker_old ~/.docker

vagrant@tiger-01:~$ calicoctl
Traceback (most recent call last):
  File "<string>", line 64, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/bgp.py", line 38, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/connectors.py", line 44, in <module>
  File "site-packages/docker/client.py", line 56, in __init__
  File "site-packages/docker/auth/auth.py", line 182, in load_config
  File "site-packages/docker/auth/auth.py", line 118, in parse_auth
TypeError: string indices must be integers
calicoctl returned -1

vagrant@tiger-01:~$ ls ~/.docker
config.json

vagrant@tiger-01:~$ cat ~/.docker/config.json
{
"psFormat":"table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.RunningFor}}"
}

**Comment by matthewdupre** [comment]
We use the docker client now instead, so closing this.
