### ISSUE TITLE
calico-node doesn't load ip_tables module

### ISSUE THREAD

**Issue by hanikesn** [projectcalico/calico-containers#910]
After upgrading from docker 1.8.3 to 1.10.3 with `--iptables=false` set for the docker daemon, the `ip_tables` module doesn't get loaded by docker anymore. This means that the `calico-node` container can't upate iptables rules and fails setting up networking for containers (as it can't load the `ip_tables` module from inside the container).

Some logs:
```
2016-04-06 10:12:33,353 [INFO][402/4] calico.felix.frules 231: IPIP disabled or no tunnel address set: removing MASQUERADE rule.
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables-save v1.4.21: Cannot initialize: iptables who? (do you need to insmod?)

modprobe: can't change directory to '/lib/modules': No such file or directory
iptables-save v1.4.21: Cannot initialize: iptables who? (do you need to insmod?)

2016-04-06 10:12:33,368 [INFO][402/1] calico.felix.fetcd 531: etcd driver status changed to resync
2016-04-06 10:12:33,370 [INFO][402/5] calico.felix.fiptables 485: IptablesUpdater<v6-filter,queue_len=0,live=True,msg=None> no updates in this batch.
2016-04-06 10:12:33,371 [INFO][402/6] calico.felix.fiptables 485: IptablesUpdater<v6-raw,queue_len=0,live=True,msg=None> no updates in this batch.
2016-04-06 10:12:33,371 [ERROR][402/7] calico.felix.actor 320: Exception processing M61eb61ab87cbb589 (_load_chain_names_from_iptables)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/actor.py", line 318, in _step
    result = msg.method()
  File "/usr/lib/python2.7/site-packages/calico/felix/fiptables.py", line 189, in _load_chain_names_from_iptables
    self.table])
  File "/usr/lib/python2.7/site-packages/gevent/subprocess.py", line 327, in check_output
    raise ex
CalledProcessError: Command '['iptables-save', '--table', 'nat']' returned non-zero exit status 1
2016-04-06 10:12:33,374 [INFO][402/7] calico.felix.fiptables 485: IptablesUpdater<v4-nat,queue_len=1,live=True,msg=None> no updates in this batch.
TrackedAsyncResult ('<disabled>', '<disabled>', 'IptablesUpdater(v4-nat)', '_load_chain_names_from_iptables') was leaked with exception CalledProcessError().  Dying.
```

A solution would be for `calicoctl node` to check wether the `ip_tables` module was loaded and load it before starting the `calico-node` container.

**Comment by matthewdupre** [comment]
We've changed things around so that Felix can load its own kernel modules now.  Hopefully this will include loading iptables - if you get a chance to retest this, could you please let us know if it's working in your environment?

Thanks,
Matt
